{{ config(materialized='table', schema='gold') }}

select
    md5(coalesce(cast(store_id as varchar), '')) as store_key,
    store_id,
    store_name,
    store_type,
    region,
    email,
    phone_number,
    manager_id,
    opening_date,
    store_age_years,
    size_sq_ft,
    size_category,
    employee_count,
    sales_target,
    current_sales,
    monthly_rent,
    is_active,
    sales_target_achievement_percentage,
    revenue_per_sq_ft,
    employee_efficiency,
    has_performance_issue,
    hours_weekdays,
    hours_weekends,
    hours_holidays,
    services,
    street,
    city,
    state,
    zip_code,
    country,
    last_modified_date_clean
from {{ ref('sil_store') }}